version: '3'

services:
    db:
        image: mongo
        container_name: mongodb
        volumes:
            - database:/home
        restart: always
        networks:
            - network1
    auth:
        build: ./auth
        container_name: auth
        restart: always
        ports:
            - '4000:4000'
        networks:
            - network1
            - network2
    http:
        build: ./http
        container_name: http
        volumes:
            - httpvolume:/httpvol
        ports:
            - '4004:4004'
        networks:
            - network2

volumes:
    database:
    httpvolume:
networks:
    network1:
    network2:

        