version: '3'

services:
    db:
        container_name: mongodb
        image: mongo:3.6 
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        volumes:
            - mongo:/data/db
        networks:
            - dbnet
    
    auth:
        build: ./auth
        container_name: auth
        ports:
            - '8888:8888'
        networks:
            - dbnet

volumes:
    mongo:
        driver: local
networks:
    dbnet:
        driver: bridge