version: '3'

services:
    db:
        image: mongo
        container_name: mongodb
        volumes:
            - database:/home
        restart: always
        networks:
            - network1
    auth:
        image: joana/auth:latest
        build: ./auth
        container_name: auth
        restart: always
        ports:
            - '4000:4000'
        networks:
            - network1

volumes:
    database:
networks:
    network1:

        